/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ro_qui_apps_JNIGameInterface */

#ifndef _Included_ro_qui_apps_JNIGameInterface
#define _Included_ro_qui_apps_JNIGameInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ro_qui_apps_JNIGameInterface
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ro_qui_apps_JNIGameInterface_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ro_qui_apps_JNIGameInterface
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ro_qui_apps_JNIGameInterface_onSurfaceCreated
  (JNIEnv *, jclass);

/*
 * Class:     ro_qui_apps_JNIGameInterface
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ro_qui_apps_JNIGameInterface_onDrawFrame
  (JNIEnv *, jclass);

/*
 * Class:     ro_qui_apps_JNIGameInterface
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ro_qui_apps_JNIGameInterface_onSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ro_qui_apps_JNIGameInterface
 * Method:    onTouchEvent
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_ro_qui_apps_JNIGameInterface_onTouchEvent
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
